### ISSUE TITLE
Selecting Templates

### ISSUE THREAD

**Issue by roshangm1** [roshangm1/nerdants-tech-portal#1]

**Comment by warewolf22** [comment]
http://demo.alxmedia.se/hueman
YO KASTO HOLA

**Comment by roshangm1** [comment]
Ramro xa. Let's list out some more.

**Comment by warewolf22** [comment]
lala khoj dai halamla

**Comment by warewolf22** [comment]
https://www.youtube.com/watch?v=LU9ALgdM3GI

**Comment by warewolf22** [comment]
https://colorlib.com/wp/free-magazine-wordpress-themes/

**Comment by roshangm1** [comment]
It's not a template. Son of Satya Murthy re.

**Comment by warewolf22** [comment]
mistake vaye chha maile aahile feri hale ko chhu

**Comment by Bloodskate** [comment]
http://preview.themeforest.net/item/ruaha-personal-blog-bootstrap-template/full_screen_preview/11579020?ref=wpfreeware

**Comment by Bloodskate** [comment]
http://preview.themeforest.net/item/grid312-professional-blog-html-template/full_screen_preview/12415321?ref=wpfreeware

**Comment by Bloodskate** [comment]
http://demo2.themewarrior.com/noticia/
 http://themes.webinane.com/wp/crazy-blog/magazine/
 http://themes.webinane.com/wp/crazy-blog/magazine/magazine-7/

**Comment by roshangm1** [comment]
http://demo.alxmedia.se/hueman
Yo theme fix bhayo
